image: maven:3.9-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    expire_in: 2 weeks
    paths:
      - target/Habbo-*.jar

  
