package com.eu.habbo.habbohotel.wired;

public enum WiredConditionType {
    STATE_POSITION_MATCH(0),
    AVATAR_ON_FURNI(1),
    FURNI_HAS_AVATAR(2),
    HAS_FURNI_ON(3),
    AVATAR_MATCHES(4),
    AVATAR_DIRECTION(5),
    AVATAR_PERFORMING_ACTION(6),
    AVATAR_IN_GROUP(7),
    AVATAR_HAS_HANDITEM(8),
    COUNTER_TIME_MATCHES(9),
    LESS_THAN_X_ELAPSED(10),
    MORE_THAN_X_ELAPSED(11),
    FURNI_ALTITUDE_MATCHES(12),
    FURNI_MATCHES(13),
    SELECTION_AMOUNT(14),
    CAN_PERFORM_MOVEMENT(15),
    AVATAR_IN_TEAM(16),
    TEAM_HAS_SCORE(17),
    TEAM_IS_WINNING(18),
    TIME_MATCHES(19),
    DATE_MATCHES(20),
    AVATAR_COUNT_IN_ROOM(21),
    CHEST_HAS_ITEMS(45),
    CHEST_HAS_FURNI_TYPE(46),



    HAS_VARIABLE(30),
    VARIABLE_VALUE_MATCHES(31),
    VARIABLE_AGE_MATCHES(32),



    //Negative Conditions
    NOT_STATE_POSITION_MATCH(50),
    NOT_AVATAR_ON_FURNI(51),
    NOT_FURNI_HAS_AVATAR(52),
    NOT_HAS_FURNI_ON(53),
    NOT_AVATAR_MATCHES(54),
    NOT_AVATAR_PERFORMING_ACTION(55),
    NOT_AVATAR_IN_GROUP(56),
    NOT_AVATAR_HAS_HANDITEM(57),
    NOT_FURNI_MATCHES(58),
    NOT_AVATAR_IN_TEAM(59),
    NOT_AVATAR_COUNT_IN_ROOM(60),
    NOT_HAS_VARIABLE(61);


    public final int code;

    WiredConditionType(int code) {
        this.code = code;
    }
}
