package com.eu.habbo.habbohotel.wired;

public enum WiredEffectType {

    TOGGLE_STATE(0),
    MOVE_ROTATE_FURNI(1),
    MOVE_ROTATE_AVATAR(2),
    MATCH_POS_STATE(3),
    TELEPORT_TO_FURNI(4),
    SHOW_MESSAGE(5),
    TOGGLE_RANDOM_STATE(6),
    EXECUTE_STACKS(7),
    CONTROL_COUNTER(8),
    ADJUST_COUNTER(9),
    TIMER_RESET(10),
    SEND_SIGNAL(11),
    TELEPORT_TO_ROOM(12), 
    SET_FURNI_ALTITUDE(13),
    CHANGE_FURNI_DIRECTION(14),
    FURNI_TO_FURNI(15),
    FURNI_TO_AVATAR(16),
    AVATAR_TO_FURNI(17),
    RELATIVE_FURNI_MOVEMENT(18),
    PLACE_TEMP_FURNI(19),
    REMOVE_TEMP_FURNI(20),
    MOVE_FURNI_AS_GROUP(21),
    MOVE_FURNI_TOWARDS_AVATAR(22),
    MOVE_FURNI_AWAY_AVATAR(23),
    JOIN_TEAM(24),
    LEAVE_TEAM(25),
    GIVE_POINTS(26),
    GIVE_PREDEFINED_POINTS(27),
    FREEZE_AVATAR(28),
    UNFREEZE_AVATAR(29),
    SET_CLICK_CONFIG(30),
    KICK_AVATAR(31),
    BOT_GIVE_HANDITEM(32),
    BOT_WALK_TO_FURNI(33),
    BOT_TELEPORT_TO_FURNI(34),
    BOT_TALK_TO_ROOM(35),
    BOT_TALK_TO_AVATAR(36),
    BOT_FOLLOW_AVATAR(37),
    BOT_CHANGE_CLOTHES(38),
    WRITE_LOGS(39),
    NEGATIVE_EXECUTE_STACKS(40),
    NEGATIVE_SEND_SIGNAL(41),
    NEGATIVE_WRITE_LOGS(42),
    CHANGE_VARIABLE_VALUE(43),
    GIVE_VARIABLE(44),
    REMOVE_VARIABLE(45),

    GIVE_CURRENCY_FROM_CHEST(46),
    GIVE_FURNI_FROM_CHEST(47),
    INITIATE_TRANSACTION(48),
    CANCEL_TRANSACTION(49);

    public final int code;

    WiredEffectType(int code) {
        this.code = code;
    }
}
